apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee-shop
  template:
    metadata:
      labels:
        app: coffee-shop
    spec:
      containers:
        - name: coffee-shop-backend
          image: coffee-shop-backend:latest  # Asegúrate de tener la imagen disponible
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: "mysql://root:password@mysql-service:3306/coffeeshopdb"
            - name: MONGO_URL
              value: "mongodb://mongo-service:27017/coffeeshopdb"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: coffee-shop-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
  selector:
    app: coffee-shop
