apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  NODE_ENV: "production"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= # Base64 de 'password'
  MYSQL_USER: dXNlcg==             # Base64 de 'user'
  MYSQL_PASSWORD: cGFzc3dvcmQ=      # Base64 de 'password'
